# Generated by Django 3.0.11 on 2021-03-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0174_merge_20201222_1031"),
        ("pretix_swap", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swapgroup",
            name="left",
        ),
        migrations.RemoveField(
            model_name="swapgroup",
            name="right",
        ),
        migrations.AddField(
            model_name="swapgroup",
            name="items",
            field=models.ManyToManyField(
                related_name="_swapgroup_items_+", to="pretixbase.Item"
            ),
        ),
    ]
