# Generated by Django 3.0.11 on 2021-03-02 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0174_merge_20201222_1031"),
        ("pretix_swap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SwapApproval",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("approved_for_cancelation_request", models.BooleanField(default=True)),
                (
                    "position",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_approval",
                        to="pretixbase.Order",
                    ),
                ),
            ],
        ),
    ]
