# Generated by Django 3.0.11 on 2021-03-01 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0174_merge_20201222_1031"),
        ("pretix_swap", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="swaprequest",
            name="target_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="pretixbase.Item",
            ),
        ),
    ]
