# Generated by Django 3.0.11 on 2021-03-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pretix_swap", "0002_swaprequest_target_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swapgroup",
            name="only_same_price",
        ),
        migrations.RemoveField(
            model_name="swapgroup",
            name="price_tolerance",
        ),
    ]
