# Generated by Django 3.0.11 on 2021-03-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pretix_swap", "0002_swapapproval"),
    ]

    operations = [
        migrations.RenameField(
            model_name="swapapproval",
            old_name="position",
            new_name="order",
        ),
    ]
