# Generated by Django 3.0.11 on 2021-06-16 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0183_auto_20210423_0829"),
        ("pretix_swap", "0002_restructure_swap_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swaprequest",
            name="target_item",
        ),
        migrations.AddField(
            model_name="swapgroup",
            name="subevents",
            field=models.ManyToManyField(
                related_name="_swapgroup_subevents_+", to="pretixbase.SubEvent"
            ),
        ),
        migrations.AddField(
            model_name="swaprequest",
            name="target_subevent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="pretixbase.SubEvent",
            ),
        ),
    ]
