# Generated by Django 3.0.11 on 2021-03-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretix_swap", "0003_auto_20210301_1033"),
    ]

    operations = [
        migrations.AddField(
            model_name="swapgroup",
            name="swap_type",
            field=models.CharField(default="s", max_length=1),
            preserve_default=False,
        ),
    ]
